### PR TITLE
Employee list 2

### LINKED ISSUE #19: User should be able to see a list of employees
## Acceptance Criteria

**Given** an HR employee wants to view employees
**When** the employee clicks on the Employees item in the navigation bar
**Then** all current employees should be listed with the following information

1. First name and last name
1. Department

### PR DESCRIPTION
**Pull request by Garcia-Julz**
# Description
The employee list should now show the correlating department that each employee belongs to.

Closes #19 
## Type of change
Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)
# Testing Instructions
Make sure to commit local changes in your branch before switching to master.
1. Ensure that connection.py contains the appropriate absolute path for your machine to test locally
2. `git checkout master`
3. `git fetch --all`
4. `git checkout Employee-List-2`
5. If you have yet inserted data for your department and employee table please do so now before testing.
insert the following queries to populate your tables with data to test with:

`INSERT INTO hrapp_department (dept_name, dept_budget)
VALUES ("transport", 35000000);`

`INSERT INTO hrapp_employee (first_name, last_name, start_date, is_supervisor, department_id)
VALUES ('Julian', 'Garcia', '2014-04-05', TRUE, 1);` 

Now you may go to http://localhost:8000/employees/ and see that the employee listed has thie department shown alongside.

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sampita** [comment]
I believe it ALMOST works, but I get an error message:
`no such column: e.department_id`

I think the key name for Department table's id is just `id`?

**Review by sampita — APPROVED** [review]
🐶🐩🐕

**Review by CassieBoyd — APPROVED** [review]
Looks good! And I learned a new thing!

**Comment by Garcia-Julz** [comment]
Hooray! 🔥

**Pull request merged**
